import { useEffect, useRef } from 'react';
import styles from '@/styles/Home.module.css';
import Head from 'next/head';

export default function Home() {
  const containerRef = useRef(null);
  const movableDivRef = useRef(null);
  const keyStateRef = useRef({});

  //Segundo cubo
  const secondBoxRef = useRef(null);
  useEffect(() => {
    const container = containerRef.current;
    const movableDiv = movableDivRef.current;
    const secondBox = secondBoxRef.current;
    const step = 2;   //Velocidad
    const pushFactor = 0.9; // Factor de reducción de velocidad durante el empuje

    const isColliding = () => {
      const movableDivRect = movableDiv.getBoundingClientRect();
      const secondBoxRect = secondBox.getBoundingClientRect();

      return (
        movableDivRect.right > secondBoxRect.left &&
        movableDivRect.left < secondBoxRect.right &&
        movableDivRect.bottom > secondBoxRect.top &&
        movableDivRect.top < secondBoxRect.bottom
      );
    };

    function handleKeyDown(event) {
      const { key } = event;

      if (!keyStateRef.current[key]) {
        keyStateRef.current[key] = true;

        switch (key) {
          case 'a':
            requestAnimationFrame(moveLeft);
            break;
          case 'w':
            requestAnimationFrame(moveUp);
            break;
          case 's':
            requestAnimationFrame(moveDown);
            break;
          case 'd':
            requestAnimationFrame(moveRight);
            break;
          default:
            break;
        }
      }
    }

    function handleKeyUp(event) {
      const { key } = event;
      keyStateRef.current[key] = false;
    }

    function moveLeft() {
      const currentLeft = parseInt(movableDiv.style.left || '0');
      if (currentLeft > 0) {
        movableDiv.style.left = `${currentLeft - step}px`;
      }
      if (keyStateRef.current['a'] && !isColliding()) {
        requestAnimationFrame(moveLeft);
      } else if (isColliding()) {
        movableDiv.style.left = `${currentLeft + step * pushFactor}px`;
      }
    }

    function moveUp() {
      const currentTop = parseInt(movableDiv.style.top || '0');
      if (currentTop > 0) {
        movableDiv.style.top = `${currentTop - step}px`;
      }
      if (keyStateRef.current['w'] && !isColliding()) {
        requestAnimationFrame(moveUp);
      } else if (isColliding()) {
        movableDiv.style.top = `${currentTop + step * pushFactor}px`;
      }
    }

    function moveDown() {
      const currentTop = parseInt(movableDiv.style.top || '0');
      const movableDivHeight = movableDiv.offsetHeight;
      const containerHeight = container.offsetHeight;
      if (currentTop + movableDivHeight < containerHeight) {
        movableDiv.style.top = `${currentTop + step}px`;
      }
      if (keyStateRef.current['s'] && !isColliding()) {
        requestAnimationFrame(moveDown);
      } else if (isColliding()) {
        movableDiv.style.top = `${currentTop - step * pushFactor}px`;
      }
    }

    function moveRight() {
      const currentLeft = parseInt(movableDiv.style.left || '0');
      const movableDivWidth = movableDiv.offsetWidth;
      const containerWidth = container.offsetWidth;
      if (currentLeft + movableDivWidth < containerWidth) {
        movableDiv.style.left = `${currentLeft + step}px`;
      }
      if (keyStateRef.current['d'] && !isColliding()) {
        requestAnimationFrame(moveRight);
      } else if (isColliding()) {
        movableDiv.style.left = `${currentLeft - step * pushFactor}px`;
      }
    }

    document.addEventListener('keydown', handleKeyDown);
    document.addEventListener('keyup', handleKeyUp);

    return () => {
      document.removeEventListener('keydown', handleKeyDown);
      document.removeEventListener('keyup', handleKeyUp);
    };
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.center} ref={containerRef}>
          <div className={styles.caja} ref={movableDivRef}>
            
          </div>
          <div className={styles.secondBox} ref={secondBoxRef}></div>
        </div>
      </main>
    </>
  );
}
