import { useEffect, useRef, useState } from 'react';
import stylesMove from '@/styles/Move.module.css';
import Head from 'next/head';
import Image from 'next/image';
import styles from '@/styles/Home.module.css';
import {Player} from '../component/Player/Player'

export default function Home() {
  const containerRef = useRef(null);
  /* Personaje */
  const movableDivRef = useRef(null);
  const sombraDivRef = useRef(null);

  /* Obstaculos */
  const primerBoxRef = useRef(null);
  const secondBoxRef = useRef(null);
  const threeBoxRef = useRef(null);
  const forBoxRef = useRef(null);
  const fiveBoxRef = useRef(null);


  const keyStateRef = useRef({});
  const pressedKeysRef = useRef([]);
  const [movableDivClasses, setMovableDivClasses] = useState(`${stylesMove.sprite} ${stylesMove.spriteNotMoveS}`);
  
  /* Camara */
  const [cameraPosition, setCameraPosition] = useState({ x: 750, y: 1400 });

  const boxes = [fiveBoxRef.current, forBoxRef.current, threeBoxRef.current, secondBoxRef.current, primerBoxRef.current];


  const containerStyle = {
    position: 'relative',
    border: '1px solid rgb(22, 22, 22)',
    backgroundColor: 'white',
    height: '250vh',
    width: '250vw',
    transform: `translate(-${cameraPosition.x}px, -${cameraPosition.y}px)`
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>

        <div className={styles.center} ref={containerRef} style={containerStyle}>



          {/* Obstaculo */}
          <Image src={"/img/casa.gif"} alt="" className={styles.casaImage} width={20} height={10} />

          <div className={styles.obstacle5} ref={fiveBoxRef} />


          
          <div className={styles.obstacle4} ref={forBoxRef} />
          <div className={styles.obstacle3} ref={threeBoxRef} />
          <div className={styles.obstacle2} ref={secondBoxRef} />
          <div className={styles.obstacle} ref={primerBoxRef} />

          {/* Personaje */}
          <div className={movableDivClasses} ref={movableDivRef} />

          <Image src={"/img/sombra.svg"} width={100} height={100} className={stylesMove.sombra1} ref={sombraDivRef} />

          {/* Agregamos el componente Player aquí */}
          <Player
            containerRef={containerRef}
            movableDivRef={movableDivRef}
            sombraDivRef={sombraDivRef}
            boxesRefs={[fiveBoxRef, forBoxRef, threeBoxRef, secondBoxRef, primerBoxRef]}
            keyStateRef={keyStateRef}
            pressedKeysRef={pressedKeysRef}
            setMovableDivClasses={setMovableDivClasses}
            setCameraPosition={setCameraPosition}
          />
        </div>
      </main>
    </>
  );
}
